version: '3'

services:
  apache:
    image: php:7.4-apache
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html

  mariadb:
    image: bitnami/mariadb:10.6.16
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      MARIADB_SKIP_TEST_DB: yes
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      UPLOAD_LIMIT: "1024M"
    ports:
      - "8181:80"